[package]
name = "ray-tracing-weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
rand = { version = "0.8.5", features = ["small_rng"] }

[dev-dependencies]
color-eyre = "0.6.3"
