name: Bencher CI

on:
  push:
    branches: main

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    steps:
      - name: Install Valgrind
        run: sudo apt-get -y install valgrind
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Track base branch criterion benchmarks with Bencher
        run: |
          bencher run \
          --project raytracing-weekend \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --adapter rust_criterion \
          --err \
          "cargo bench --bench criterion_grid_scene --bench criterion_dielectric_scene --bench criterion_grid_pixel --bench criterion_dielectric_pixel --bench criterion_many_scene"
      - name: Track base branch iai benchmarks with Bencher
        run: |
          bencher run \
          --project raytracing-weekend \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --adapter rust_iai \
          --err \
          "cargo bench --bench iai_grid_scene --bench iai_dielectric_scene --bench iai_grid_pixel --bench iai_dielectric_pixel"
